---

- name: Install aptitude using apt
  become: yes
  apt:
    name: aptitude
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install software
  become: yes
  apt:
    name:
      - unzip
      - python3-pip
      - python3-setuptools
    state: latest
    update_cache: yes

- name: Install python-consul package
  pip:
    name: 
      - python-consul

- name: Download consul archive
  get_url:
    url: https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip
    dest: /home/ubuntu
  when: (create_monitoring is defined and create_monitoring) or (ansible_hostname == cluster_name | lower + consul_kv_host)

- name: Unarchive consul binary file
  become: yes
  unarchive:
    src: /home/ubuntu/consul_{{ consul_version }}_linux_amd64.zip
    dest: /usr/bin
    remote_src: yes
  when: (create_monitoring is defined and create_monitoring) or (ansible_hostname == cluster_name | lower + consul_kv_host)

- name: Remove downloaded archive
  file:
    path: /home/ubuntu/consul_{{ consul_version }}_linux_amd64.zip
    state: absent
  when: (create_monitoring is defined and create_monitoring) or (ansible_hostname == cluster_name | lower + consul_kv_host)
