---

- name: Daemon_reload
  systemd: daemon_reload=yes
  when: (create_monitoring is defined and create_monitoring) or (ansible_hostname == cluster_name | lower + consul_kv_host)

- name: Start consul service
  systemd:
    name: consul.service
    state: started
    enabled: True
  when: (create_monitoring is defined and create_monitoring) or (ansible_hostname == cluster_name | lower + consul_kv_host)
