// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protofile.proto

package ansible

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cluster_EntityStatusTypes int32

const (
	Cluster_UNKNOWN Cluster_EntityStatusTypes = 0
	Cluster_INITED  Cluster_EntityStatusTypes = 1
	Cluster_FAILED  Cluster_EntityStatusTypes = 2
	Cluster_CREATED Cluster_EntityStatusTypes = 3
	Cluster_DOWN    Cluster_EntityStatusTypes = 4
)

var Cluster_EntityStatusTypes_name = map[int32]string{
	0: "UNKNOWN",
	1: "INITED",
	2: "FAILED",
	3: "CREATED",
	4: "DOWN",
}

var Cluster_EntityStatusTypes_value = map[string]int32{
	"UNKNOWN": 0,
	"INITED":  1,
	"FAILED":  2,
	"CREATED": 3,
	"DOWN":    4,
}

func (x Cluster_EntityStatusTypes) String() string {
	return proto.EnumName(Cluster_EntityStatusTypes_name, int32(x))
}

func (Cluster_EntityStatusTypes) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b28b201cc727c47d, []int{0, 0}
}

type Cluster struct {
	ID                   int32                     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string                    `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	DisplayName          string                    `protobuf:"bytes,3,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	HostURL              string                    `protobuf:"bytes,4,opt,name=HostURL,proto3" json:"HostURL,omitempty"`
	EntityStatus         Cluster_EntityStatusTypes `protobuf:"varint,5,opt,name=EntityStatus,proto3,enum=ansible.Cluster_EntityStatusTypes" json:"EntityStatus,omitempty"`
	ClusterType          string                    `protobuf:"bytes,6,opt,name=ClusterType,proto3" json:"ClusterType,omitempty"`
	Services             []*Service                `protobuf:"bytes,7,rep,name=services,proto3" json:"services,omitempty"`
	NHosts               int32                     `protobuf:"varint,8,opt,name=NHosts,proto3" json:"NHosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Cluster) Reset()         { *m = Cluster{} }
func (m *Cluster) String() string { return proto.CompactTextString(m) }
func (*Cluster) ProtoMessage()    {}
func (*Cluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b201cc727c47d, []int{0}
}

func (m *Cluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cluster.Unmarshal(m, b)
}
func (m *Cluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cluster.Marshal(b, m, deterministic)
}
func (m *Cluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cluster.Merge(m, src)
}
func (m *Cluster) XXX_Size() int {
	return xxx_messageInfo_Cluster.Size(m)
}
func (m *Cluster) XXX_DiscardUnknown() {
	xxx_messageInfo_Cluster.DiscardUnknown(m)
}

var xxx_messageInfo_Cluster proto.InternalMessageInfo

func (m *Cluster) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Cluster) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cluster) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Cluster) GetHostURL() string {
	if m != nil {
		return m.HostURL
	}
	return ""
}

func (m *Cluster) GetEntityStatus() Cluster_EntityStatusTypes {
	if m != nil {
		return m.EntityStatus
	}
	return Cluster_UNKNOWN
}

func (m *Cluster) GetClusterType() string {
	if m != nil {
		return m.ClusterType
	}
	return ""
}

func (m *Cluster) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

func (m *Cluster) GetNHosts() int32 {
	if m != nil {
		return m.NHosts
	}
	return 0
}

type Service struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Type                 string            `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	ClusterRef           string            `protobuf:"bytes,3,opt,name=ClusterRef,proto3" json:"ClusterRef,omitempty"`
	ServiceState         string            `protobuf:"bytes,4,opt,name=ServiceState,proto3" json:"ServiceState,omitempty"`
	ServiceURL           string            `protobuf:"bytes,5,opt,name=ServiceURL,proto3" json:"ServiceURL,omitempty"`
	Config               map[string]string `protobuf:"bytes,6,rep,name=Config,proto3" json:"Config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	DisplayName          string            `protobuf:"bytes,7,opt,name=DisplayName,proto3" json:"DisplayName,omitempty"`
	EntityStatus         string            `protobuf:"bytes,8,opt,name=EntityStatus,proto3" json:"EntityStatus,omitempty"`
	Version              string            `protobuf:"bytes,9,opt,name=Version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b201cc727c47d, []int{1}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Service) GetClusterRef() string {
	if m != nil {
		return m.ClusterRef
	}
	return ""
}

func (m *Service) GetServiceState() string {
	if m != nil {
		return m.ServiceState
	}
	return ""
}

func (m *Service) GetServiceURL() string {
	if m != nil {
		return m.ServiceURL
	}
	return ""
}

func (m *Service) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Service) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *Service) GetEntityStatus() string {
	if m != nil {
		return m.EntityStatus
	}
	return ""
}

func (m *Service) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type TaskStatus struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskStatus) Reset()         { *m = TaskStatus{} }
func (m *TaskStatus) String() string { return proto.CompactTextString(m) }
func (*TaskStatus) ProtoMessage()    {}
func (*TaskStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b201cc727c47d, []int{2}
}

func (m *TaskStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskStatus.Unmarshal(m, b)
}
func (m *TaskStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskStatus.Marshal(b, m, deterministic)
}
func (m *TaskStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskStatus.Merge(m, src)
}
func (m *TaskStatus) XXX_Size() int {
	return xxx_messageInfo_TaskStatus.Size(m)
}
func (m *TaskStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TaskStatus proto.InternalMessageInfo

func (m *TaskStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type NewID struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewID) Reset()         { *m = NewID{} }
func (m *NewID) String() string { return proto.CompactTextString(m) }
func (*NewID) ProtoMessage()    {}
func (*NewID) Descriptor() ([]byte, []int) {
	return fileDescriptor_b28b201cc727c47d, []int{3}
}

func (m *NewID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewID.Unmarshal(m, b)
}
func (m *NewID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewID.Marshal(b, m, deterministic)
}
func (m *NewID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewID.Merge(m, src)
}
func (m *NewID) XXX_Size() int {
	return xxx_messageInfo_NewID.Size(m)
}
func (m *NewID) XXX_DiscardUnknown() {
	xxx_messageInfo_NewID.DiscardUnknown(m)
}

var xxx_messageInfo_NewID proto.InternalMessageInfo

func (m *NewID) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func init() {
	proto.RegisterEnum("ansible.Cluster_EntityStatusTypes", Cluster_EntityStatusTypes_name, Cluster_EntityStatusTypes_value)
	proto.RegisterType((*Cluster)(nil), "ansible.Cluster")
	proto.RegisterType((*Service)(nil), "ansible.Service")
	proto.RegisterMapType((map[string]string)(nil), "ansible.Service.ConfigEntry")
	proto.RegisterType((*TaskStatus)(nil), "ansible.TaskStatus")
	proto.RegisterType((*NewID)(nil), "ansible.NewID")
}

func init() { proto.RegisterFile("protofile.proto", fileDescriptor_b28b201cc727c47d) }

var fileDescriptor_b28b201cc727c47d = []byte{
	// 505 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x9d, 0xd8, 0x4e, 0x27, 0x25, 0x98, 0x01, 0x95, 0x55, 0x85, 0x50, 0xb4, 0xe2, 0x10,
	0x09, 0x14, 0xa1, 0x80, 0xc4, 0x87, 0xc4, 0x21, 0xc4, 0x29, 0xb5, 0xa8, 0x5c, 0x69, 0x9b, 0xc0,
	0xd9, 0x85, 0x0d, 0xb2, 0x1a, 0x9c, 0xc8, 0xbb, 0x2e, 0xf2, 0x1f, 0xe6, 0xc0, 0xaf, 0x40, 0xfb,
	0x51, 0xd7, 0x71, 0x39, 0x70, 0x9b, 0x79, 0xf3, 0xbc, 0xf3, 0xe6, 0xcd, 0x18, 0xee, 0xef, 0x8a,
	0xad, 0xdc, 0xae, 0xb3, 0x0d, 0x9f, 0xe8, 0x08, 0x83, 0x34, 0x17, 0xd9, 0xe5, 0x86, 0xd3, 0x3f,
	0x2e, 0x04, 0xf3, 0x4d, 0x29, 0x24, 0x2f, 0x70, 0x08, 0x6e, 0x1c, 0x11, 0x67, 0xe4, 0x8c, 0x3d,
	0xe6, 0xc6, 0x11, 0x22, 0xf4, 0x92, 0xf4, 0x27, 0x27, 0xee, 0xc8, 0x19, 0x1f, 0x30, 0x1d, 0xe3,
	0x08, 0x06, 0x51, 0x26, 0x76, 0x9b, 0xb4, 0xd2, 0xa5, 0xae, 0x2e, 0x35, 0x21, 0x24, 0x10, 0x9c,
	0x6e, 0x85, 0x5c, 0xb1, 0x33, 0xd2, 0xd3, 0xd5, 0x9b, 0x14, 0x4f, 0xe0, 0x70, 0x91, 0xcb, 0x4c,
	0x56, 0x17, 0x32, 0x95, 0xa5, 0x20, 0xde, 0xc8, 0x19, 0x0f, 0xa7, 0x74, 0x62, 0xb5, 0x4c, 0xac,
	0x8e, 0x49, 0x93, 0xb4, 0xac, 0x76, 0x5c, 0xb0, 0xbd, 0xef, 0x94, 0x06, 0x4b, 0x55, 0x55, 0xe2,
	0x1b, 0x0d, 0x0d, 0x08, 0x5f, 0x40, 0x5f, 0xf0, 0xe2, 0x3a, 0xfb, 0xc6, 0x05, 0x09, 0x46, 0xdd,
	0xf1, 0x60, 0x1a, 0xd6, 0x5d, 0x2e, 0x4c, 0x81, 0xd5, 0x0c, 0x3c, 0x02, 0x3f, 0x51, 0x1a, 0x05,
	0xe9, 0xeb, 0xd9, 0x6d, 0x46, 0xcf, 0xe1, 0xc1, 0x1d, 0x29, 0x38, 0x80, 0x60, 0x95, 0x7c, 0x4e,
	0xce, 0xbf, 0x26, 0x61, 0x07, 0x01, 0xfc, 0x38, 0x89, 0x97, 0x8b, 0x28, 0x74, 0x54, 0x7c, 0x32,
	0x8b, 0xcf, 0x16, 0x51, 0xe8, 0x2a, 0xd2, 0x9c, 0x2d, 0x66, 0xaa, 0xd0, 0xc5, 0x3e, 0xf4, 0x22,
	0x45, 0xef, 0xd1, 0xdf, 0x2e, 0x04, 0xb6, 0x7d, 0x6d, 0xae, 0xd3, 0x30, 0x17, 0xa1, 0xa7, 0x27,
	0xb2, 0x86, 0xeb, 0x51, 0x9e, 0x02, 0xd8, 0xc9, 0x18, 0x5f, 0x5b, 0xbf, 0x1b, 0x08, 0x52, 0x38,
	0xb4, 0x4f, 0x2a, 0x95, 0xdc, 0x7a, 0xbe, 0x87, 0xa9, 0x37, 0x6c, 0xae, 0xb6, 0xe2, 0x99, 0x37,
	0x6e, 0x11, 0x7c, 0x0d, 0xfe, 0x7c, 0x9b, 0xaf, 0xb3, 0x1f, 0xc4, 0xd7, 0x66, 0x3d, 0x69, 0x9b,
	0x35, 0x31, 0xe5, 0x45, 0x2e, 0x8b, 0x8a, 0x59, 0x6e, 0xfb, 0x14, 0x82, 0xbb, 0xa7, 0x40, 0x5b,
	0x0b, 0xef, 0x1b, 0x6d, 0x7b, 0xcb, 0x24, 0x10, 0x7c, 0xe1, 0x85, 0xc8, 0xb6, 0x39, 0x39, 0x30,
	0xe7, 0x62, 0xd3, 0xe3, 0x77, 0x30, 0x68, 0xb4, 0xc5, 0x10, 0xba, 0x57, 0xbc, 0xb2, 0x7e, 0xa9,
	0x10, 0x1f, 0x81, 0x77, 0x9d, 0x6e, 0xca, 0x1b, 0xbf, 0x4c, 0xf2, 0xde, 0x7d, 0xeb, 0xd0, 0x67,
	0x00, 0xcb, 0x54, 0x5c, 0xd9, 0x16, 0x47, 0xe0, 0x5b, 0x01, 0xe6, 0x63, 0x9b, 0xd1, 0xc7, 0xe0,
	0x25, 0xfc, 0x57, 0x1c, 0xb5, 0x0f, 0x7f, 0x7a, 0x0a, 0xf7, 0x66, 0xc6, 0x00, 0x56, 0xe6, 0x39,
	0x2f, 0xf0, 0x0d, 0x00, 0x2b, 0x73, 0x8b, 0x61, 0xd8, 0xbe, 0xd8, 0xe3, 0x87, 0x35, 0x72, 0xdb,
	0x96, 0x76, 0x5e, 0x3a, 0xd3, 0x1d, 0xb8, 0xd1, 0x47, 0x7c, 0x0e, 0xde, 0x27, 0x2e, 0xe3, 0xe8,
	0x1f, 0x5f, 0x0e, 0x6b, 0x44, 0x4b, 0xa1, 0x1d, 0xfc, 0x00, 0xb8, 0xda, 0x7d, 0x4f, 0x25, 0xb7,
	0x14, 0xb3, 0xc2, 0xff, 0xed, 0x79, 0xe9, 0xeb, 0x1f, 0xfc, 0xd5, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x4a, 0x51, 0xf5, 0x73, 0xf3, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AnsibleRunnerClient is the client API for AnsibleRunner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AnsibleRunnerClient interface {
	RunAnsible(ctx context.Context, in *Cluster, opts ...grpc.CallOption) (AnsibleRunner_RunAnsibleClient, error)
}

type ansibleRunnerClient struct {
	cc *grpc.ClientConn
}

func NewAnsibleRunnerClient(cc *grpc.ClientConn) AnsibleRunnerClient {
	return &ansibleRunnerClient{cc}
}

func (c *ansibleRunnerClient) RunAnsible(ctx context.Context, in *Cluster, opts ...grpc.CallOption) (AnsibleRunner_RunAnsibleClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AnsibleRunner_serviceDesc.Streams[0], "/ansible.AnsibleRunner/RunAnsible", opts...)
	if err != nil {
		return nil, err
	}
	x := &ansibleRunnerRunAnsibleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AnsibleRunner_RunAnsibleClient interface {
	Recv() (*TaskStatus, error)
	grpc.ClientStream
}

type ansibleRunnerRunAnsibleClient struct {
	grpc.ClientStream
}

func (x *ansibleRunnerRunAnsibleClient) Recv() (*TaskStatus, error) {
	m := new(TaskStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AnsibleRunnerServer is the server API for AnsibleRunner service.
type AnsibleRunnerServer interface {
	RunAnsible(*Cluster, AnsibleRunner_RunAnsibleServer) error
}

// UnimplementedAnsibleRunnerServer can be embedded to have forward compatible implementations.
type UnimplementedAnsibleRunnerServer struct {
}

func (*UnimplementedAnsibleRunnerServer) RunAnsible(req *Cluster, srv AnsibleRunner_RunAnsibleServer) error {
	return status.Errorf(codes.Unimplemented, "method RunAnsible not implemented")
}

func RegisterAnsibleRunnerServer(s *grpc.Server, srv AnsibleRunnerServer) {
	s.RegisterService(&_AnsibleRunner_serviceDesc, srv)
}

func _AnsibleRunner_RunAnsible_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Cluster)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AnsibleRunnerServer).RunAnsible(m, &ansibleRunnerRunAnsibleServer{stream})
}

type AnsibleRunner_RunAnsibleServer interface {
	Send(*TaskStatus) error
	grpc.ServerStream
}

type ansibleRunnerRunAnsibleServer struct {
	grpc.ServerStream
}

func (x *ansibleRunnerRunAnsibleServer) Send(m *TaskStatus) error {
	return x.ServerStream.SendMsg(m)
}

var _AnsibleRunner_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ansible.AnsibleRunner",
	HandlerType: (*AnsibleRunnerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunAnsible",
			Handler:       _AnsibleRunner_RunAnsible_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protofile.proto",
}

// DBClient is the client API for DB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DBClient interface {
	GetID(ctx context.Context, in *Cluster, opts ...grpc.CallOption) (*NewID, error)
	UpdateClusterState(ctx context.Context, in *Cluster, opts ...grpc.CallOption) (*TaskStatus, error)
}

type dBClient struct {
	cc *grpc.ClientConn
}

func NewDBClient(cc *grpc.ClientConn) DBClient {
	return &dBClient{cc}
}

func (c *dBClient) GetID(ctx context.Context, in *Cluster, opts ...grpc.CallOption) (*NewID, error) {
	out := new(NewID)
	err := c.cc.Invoke(ctx, "/ansible.DB/GetID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) UpdateClusterState(ctx context.Context, in *Cluster, opts ...grpc.CallOption) (*TaskStatus, error) {
	out := new(TaskStatus)
	err := c.cc.Invoke(ctx, "/ansible.DB/UpdateClusterState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBServer is the server API for DB service.
type DBServer interface {
	GetID(context.Context, *Cluster) (*NewID, error)
	UpdateClusterState(context.Context, *Cluster) (*TaskStatus, error)
}

// UnimplementedDBServer can be embedded to have forward compatible implementations.
type UnimplementedDBServer struct {
}

func (*UnimplementedDBServer) GetID(ctx context.Context, req *Cluster) (*NewID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetID not implemented")
}
func (*UnimplementedDBServer) UpdateClusterState(ctx context.Context, req *Cluster) (*TaskStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateClusterState not implemented")
}

func RegisterDBServer(s *grpc.Server, srv DBServer) {
	s.RegisterService(&_DB_serviceDesc, srv)
}

func _DB_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cluster)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ansible.DB/GetID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).GetID(ctx, req.(*Cluster))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_UpdateClusterState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Cluster)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).UpdateClusterState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ansible.DB/UpdateClusterState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).UpdateClusterState(ctx, req.(*Cluster))
	}
	return interceptor(ctx, in, info, handler)
}

var _DB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ansible.DB",
	HandlerType: (*DBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetID",
			Handler:    _DB_GetID_Handler,
		},
		{
			MethodName: "UpdateClusterState",
			Handler:    _DB_UpdateClusterState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protofile.proto",
}
