---

- name: Run example training
  shell: TF_CONFIG=$(cat {{ tensorflow_config_path }}/tf_config.json) {{ tensorflow_venv_path }}/bin/python3 {{ tensorflow_project_path }}/distributed-tf-example/train_mnist.py -b 32 -e 3
  register: output_log
  ignore_errors: yes
  when: tensorflow_run_example

- name: Save log
  copy:
    content: "{{ output_log }}"
    dest: /home/ubuntu/training_log.log
  when: tensorflow_run_example
