---
# tasks for Centos 7
- name: Install necessary packages
  yum:
    name:
      - "yum-utils"
      - "device-mapper-persistent-data"
      - lvm2
    state: latest
    update_cache: yes

- name: Add repository
  command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: Install docker
  yum:
    name: "docker-ce"
    state: latest
    update_cache: yes

- name: Install python
  yum:
    name: "{{ item }}"
    state: latest
  loop: ['python3','python3-pip', 'python3-setuptools']

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3
    extra_args: --upgrade
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: latest
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes