---
# tasks for Centos 7
- name: Install necessary packages
  dnf:
    name:
      - "yum-utils"
      - "device-mapper-persistent-data"
      - lvm2
    state: latest
    update_cache: yes

- name: Add repository
  command: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo"

- name: Install lvm2
  dnf:
    name: lvm2
    state: latest

- name: Install docker
  dnf:
    name: "docker-ce"
    state: latest
    update_cache: yes

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    executable: pip3
    extra_args: --upgrade

- name: Install Docker SDK for Python
  pip:
    name: docker
    state: latest

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes