---
- name: generating key for hadoop user
  user: name={{ hadoop_user }} generate_ssh_key=yes
  when:
    - create_master is defined and create_master or create_master_slave is defined and create_master_slave
    - inventory_hostname == active_master_inventory_hostname
  tags: prepare

- name: get the public key
  fetch: src="/home/{{ hadoop_user }}/.ssh/id_rsa.pub" dest="files/keys/{{ cluster_name }}.pub" flat=yes
  when:
    - create_master is defined and create_master or create_master_slave is defined and create_master_slave
    - inventory_hostname == active_master_inventory_hostname
  tags: prepare

- name: get the private key
  fetch: src="/home/{{ hadoop_user }}/.ssh/id_rsa" dest="files/keys/{{ cluster_name }}" flat=yes
  when:
    - create_master is defined and create_master or create_master_slave is defined and create_master_slave
    - inventory_hostname == active_master_inventory_hostname
  tags: prepare

- name: deploy authorized keys
  become: yes
  become_user: root
  authorized_key: user={{ hadoop_user }} key={{ lookup('file', 'files/keys/{{ cluster_name }}.pub') }}
  when:
    - create_master is defined and create_master or create_master_slave is defined and create_master_slave
  tags: prepare

- name: deploy ssh-keys
  become: yes
  become_user: root
  copy: src="files/keys/{{ cluster_name }}" dest="/home/{{ hadoop_user }}/.ssh/{{ cluster_name }}"
  when:
    - create_master is defined and create_master or create_master_slave is defined and create_master_slave
  tags: prepare

- name: distribute ssh config
  become: yes
  become_user: root
  template: src=templates/config.j2 dest="/home/{{ hadoop_user }}/.ssh/config"
  tags: prepare

- name: modify /etc/hosts
  become: yes
  become_user: root
  template: 
    src: templates/hosts.j2
    dest: /etc/hosts
  tags: prepare

- name: Add public keys to authorized keys
  lineinfile:
    path: /home/{{ hadoop_user }}/.ssh/authorized_keys
    state: present
    create: yes
    line: "{{ item }}"
  with_items: "{{ public_keys }}"
  when: public_keys is defined and public_keys | length > 0