---

- name: Register master facts
  os_server_info:
    filters:
      metadata:
        group: "{{ cluster_name }}_master"
  register: master_info

- name: Make up master inventory
  add_host:
    name: "{{ item.name }}"
    groups: "{{ cluster_name }}_master"
    ansible_host: "{{ item.public_v4  if item.public_v4 != '' else item.private_v4 }}"
    ansible_ssh_host: "{{ item.interface_ip if item.interface_ip != '' else item.private_v4 }}"
    ansible_user: "{{ hadoop_user }}"
    openstack: "{{ item }}"
  with_items:
    - "{{ master_info.openstack_servers }}"

- name: Register slaves facts
  os_server_info:
    filters:
      metadata:
        group: "{{ cluster_name }}_slaves"
  register: slaves_info

- name: Make up slaves inventory
  add_host:
    name: "{{ item.name }}"
    groups: "{{ cluster_name }}_slaves"
    ansible_host: "{{ item.public_v4  if item.public_v4 != '' else item.private_v4 }}"
    ansible_ssh_host: "{{ item.interface_ip if item.interface_ip != '' else item.private_v4 }}"
    ansible_user: "{{ hadoop_user }}"
    openstack: "{{ item }}"
  with_items:
    - "{{ slaves_info.openstack_servers }}"

- name: Register storage facts
  os_server_info:
    filters:
      metadata:
        group: "{{ cluster_name }}_storage"
  register: storage_info
  when: create_storage is defined and create_storage

- name: Make up storage inventory
  add_host:
    name: "{{ item.name }}"
    groups: "{{ cluster_name }}_storage"
    ansible_host: "{{ item.public_v4  if item.public_v4 != '' else item.private_v4 }}"
    ansible_ssh_host: "{{ item.interface_ip if item.interface_ip != '' else item.private_v4 }}"
    ansible_user: "{{ hadoop_user }}"
    openstack: "{{ item }}"
  with_items:
    - "{{ storage_info.openstack_servers }}"
  when: create_storage is defined and create_storage

- name: Register monitoring facts
  os_server_facts:
    filters:
      metadata:
        group: "{{ cluster_name }}_monitoring"
  register: monitoring_info
  when: create_monitoring is defined and create_monitoring

- name: Make up monitoring inventory
  add_host:
    name: "{{ item.name }}"
    groups: "{{ cluster_name }}_monitoring"
    ansible_host: "{{ item.public_v4  if item.public_v4 != '' else item.private_v4 }}"
    ansible_ssh_host: "{{ item.interface_ip if item.interface_ip != '' else item.private_v4 }}"
    ansible_user: "{{ hadoop_user }}"
    openstack: "{{ item }}"
  with_items:
    - "{{ monitoring_info.openstack_servers }}"
  when: create_monitoring is defined and create_monitoring
