## You can specify path to this file in the first arg of go run commands

## Openstack

os_key_name: OS_KEY_NAME
virtual_network: NETWORK
os_image: OS_IMAGE
floating_ip_pool: IP_POOL
os_version: VERSION #stein or liberty or ussuri


## Vault

token: ROOT_TOKEN
vault_addr: VAULT_ADDR
os_key: BUCKET_PATH
cb_key: BUCKET_PATH
ssh_key: BUCKET_PATH
hydra_key: BUCKET_PATH

## Mirrors

use_mirror: true
mirror_address: MIRROR_ADDR

registry_key: BUCKET_PATH
docker_selfsigned_registry: true
docker_selfsigned_registry_ip: DOCKER_ADDR
docker_selfsigned_registry_url: URL
docker_cert_path: PATH

#auth
use_auth: true
authorization_model: none #none or oauth2 or keystone
admin_group: admin
session_idle_timeout: 480 #time in minutes, controls the maximum length of time a session can be inactive before it expires
session_lifetime: 960 #time in minutes, controls the maximum length of time that a session is valid for before it expires


#hydra auth params
hydra_admin: HYDRA_ADDR
hydra_client: HYDRA_ADDR

#keystone params
keystone_addr: KEYSTONE_ADDR

#cluster logs
logs_output: file #file or logstash
logs_file_path: PATH
logstash_addr: LOGSTASH_ADDR
elastic_addr: ELASTIC_ADDR