---

- name: Delete default repos
  become: yes
  file:
    path: "/etc/yum.repos.d"
    state: absent
  when: use_package_mirror

- name: Make clean repo directory
  become: yes
  file:
    path: "/etc/yum.repos.d"
    state: directory
  when: use_package_mirror

- name: create proxy repo file
  become: yes
  template:
    src: nexus.repo.j2
    dest: "/etc/yum.repos.d/nexus.repo"
    mode: 0644
  when: use_package_mirror

- name: Create .pip directory
  file:
    path: /home/centos/.pip
    state: directory
  when: use_pip_mirror

- name: Set pip mirror
  template:
    src: "pip.conf.j2"
    dest: "/home/centos/.pip/pip.conf"
  when: use_pip_mirror

- name: try to update dnf cache
  become: yes
  yum:
    update_cache: yes
  register: dnf_ok
  ignore_errors: yes

# TODO: add condition to ignore when mirror is used
- name: set new AppStream repo if dnf update failed on centos8
  become: yes
  lineinfile:
    path: "/etc/yum.repos.d/CentOS-Linux-AppStream.repo"
    line: "baseurl=http://vault.centos.org/$contentdir/$releasever/AppStream/$basearch/os/"
  when:
    - dnf_ok.rc != 0
    - ansible_distribution_major_version == "8"

# TODO: add condition to ignore when mirror is used
- name: set new BaseOS repo if dnf update failed on centos8
  become: yes
  lineinfile:
    path: "/etc/yum.repos.d/CentOS-Linux-BaseOS.repo"
    line: "baseurl=http://vault.centos.org/$contentdir/$releasever/BaseOS/$basearch/os/"
  when:
    - dnf_ok.rc != 0
    - ansible_distribution_major_version == "8"

# TODO: add condition to ignore when mirror is used
- name: Enable powertools
  become: true
  shell: yum config-manager --set-enabled powertools
  when: ansible_distribution_major_version == "8"

# TODO: add condition to ignore when mirror is used
- name: set new BaseOS repo if dnf update failed on centos8
  become: yes
  lineinfile:
    path: "/etc/yum.repos.d/CentOS-Linux-PowerTools.repo"
    line: "baseurl=http://vault.centos.org/$contentdir/$releasever/PowerTools/$basearch/os/"
  when:
    - dnf_ok.rc != 0
    - ansible_distribution_major_version == "8"

# TODO: add condition to ignore when mirror is used
- name: install epel-release on centos
  become: yes
  yum:
    name:
      - "epel-release"
    update_cache: yes

# TODO: add condition to ignore when mirror is used
- name: install dnf on centos7
  become: yes
  yum:
    name:
      - dnf
    update_cache: yes
  when:
    - ansible_distribution_major_version == "7"

- name: install python3, java, dstat and rsync packages, update systemd
  become: yes
  dnf:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      - dstat
      - rsync
      - systemd
      - java
      - git
    update_cache: yes

- name: disable net.ipv6.conf.all.disable_ipv6
  become: yes
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present

- name: disable net.ipv6.conf.lo.disable_ipv6
  become: yes
  sysctl: name=net.ipv6.conf.lo.disable_ipv6 value=1 state=present

- name: increase hard file limits
  become: yes
  pam_limits: domain=* limit_type=hard limit_item=nofile value=1000000

- name: increase soft file limits
  become: yes
  pam_limits: domain=* limit_type=soft limit_item=nofile value=1000000

- name: create hadoop group
  become: yes
  group: name=hadoop state=present

- name: create hadoop user
  become: yes
  user: name={{ hadoop_user }} comment="Hadoop user" group=hadoop shell=/bin/bash