---
- name: create jupyter user
  user:
    name: "{{ jupyter_user }}"
    home: "{{ jupyter_home }}"
    state: present
    shell: /bin/bash
  become: yes

- include_tasks: "{{ ansible_distribution }}.yml"

- include_tasks: venv.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: set jupyter service config path (jupyter-notebook)
  set_fact:
    jupyter_service_conf_path: "{{ jupyter_conf_dir }}/jupyter_notebook_config.py"
  when: jupyter_version == "jupyter-notebook"

- name: set jupyter service config path (jupyter-lab)
  set_fact:
    jupyter_service_conf_path: "{{ jupyter_conf_dir }}/jupyter_notebook_config.py"
  when: jupyter_version == "jupyter-lab"

# TODO: manually set ansible_python_interpreter because ansible uses /usr/bin/python running pip module for some reason
- name: include specific tasks for required jupyter version
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  include_tasks: "{{ jupyter_version }}.yml"

- include_tasks: service.yml

- include_tasks: IRkernel/main.yml
  when: jupyter_install_irkernel

- include_tasks: sparkmagic/main.yml
  when: jupyter_install_sparkmagic and deploy_spark is defined and deploy_spark
