---
- name: create jupyter user
  user:
    name: "{{ jupyter_user }}"
    home: "{{ jupyter_home }}"
    state: present
    shell: /bin/bash
  become: yes

- include_tasks: "{{ ansible_distribution }}.yml"

- include_tasks: venv.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: set jupyter service config path (jupyter-notebook)
  set_fact:
    jupyter_service_conf_path: "{{ jupyter_conf_dir }}/jupyter_notebook_config.py"
  when: jupyter_version == "jupyter-notebook"

- name: set jupyter service config path (jupyter-lab)
  set_fact:
    jupyter_service_conf_path: "{{ jupyter_conf_dir }}/jupyter_notebook_config.py"
  when: jupyter_version == "jupyter-lab"

- include_tasks: "{{ jupyter_version }}.yml"

- include_tasks: service.yml

- name: Print
  debug:
    var: jupyter_install_irkernel

- name: Print
  debug:
    var: jupyter_install_sparkmagic

- name: Print
  debug:
    var: deploy_spark
  when: deploy_spark is defined

- include_tasks: IRkernel/main.yml
  when: jupyter_install_irkernel

- include_tasks: sparkmagic/main.yml
  when: jupyter_install_sparkmagic and deploy_spark is defined and deploy_spark
