---

#FIXME: need full path to be included directly

- block:
  - include_vars: "{{roles_dir|default('roles')}}/jupyter/vars/python{{ python_version }}.yml"
  
  - name: Python version
    debug: var=python_version

  - name: Python package prefix
    debug: var=apt_pkg_pref

  - name: SparkMagic path
    debug: var=spark_magic_path

  - name: update apt cache
    apt: update_cache=yes

  - name: install packages
    package: name={{ item }} state=present
    with_items:
      - "{{apt_pkg_pref}}-dev"
      - "{{apt_pkg_pref}}-tk" #needed for pyspark
      - "{{apt_pkg_pref}}-scipy"
      - libfreetype6-dev
      - libpng12-dev
      - pkg-config
      - unzip
      - "r-base"
      - "r-base-dev"
      - libkrb5-dev #needed for sparkmagic
    register: result
    ignore_errors: True
    until: result is success
    retries: 3
    #TODO: failures are ignored

  - name: Install python3 and pip
    apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
    loop: ['python3.7','python3-pip', 'python3-setuptools']

#  - name: downlad get-pip.py
#    get_url:
#      url="https://bootstrap.pypa.io/get-pip.py"
#      dest=/tmp/
#  - name: install pip
#    raw: "{{apt_pkg_pref}} /tmp/get-pip.py"
#    become: yes
#
#  - name: install setuptools
#    become: yes
#    shell: "wget https://bootstrap.pypa.io/ez_setup.py -O - | python"

    #looks like pyparsing==2.1.2 does not work on python 3 (AttributeError: 'tuple' object has no attribute 'filename')
    #as a result of this matplotlib does not work either
#  - name: install pyparsing
#    pip: name=pyparsing state=present executable=pip{{ python_version }}
#    when: python_version|int == 3

  - name: install pip packages
    become: yes
    pip:
      name:
        - jupyter
        - numpy==1.12.0
        - pandas
        - matplotlib
        - scipy
        - seaborn
        - scikit-learn
        - pyparsing
        - sparkmagic
      state: present
      executable: pip{{ python_version }}
    register: result
    ignore_errors: True
    until: result is success
    retries: 3
    #TODO: failures are ignored

    #TODO: add 'pip install pyOpenSSL ndg-httpsclient pyasn1' to fix SNIMissingWarning in old python versions
    #      (see http://stackoverflow.com/questions/29099404/ssl-insecureplatform-error-when-using-requests-package)
  become: True
  become_user: root
  tags:
  - install
  - jupyter_install
