---

- name: acknowledge existing servers
  os_server_info:
    filters:
      metadata:
        cluster: "{{ cluster_name }}"
  register: cluster_instances

- name: print instances
  debug:
    var: cluster_instances

- name: debug
  set_fact: alive_servers="{{ alive_servers | default([]) | union([item.name]) }}"
  with_items: "{{ cluster_instances.openstack_servers }}"

- name: destroy cluster instances
  os_server:
    state: absent
    name: "{{ item }}"
  with_items: "{{ alive_servers }}"
  retries: 3
  async: 1000
  poll: 0
  register: destruction_waitress
  when: alive_servers is defined and (alive_servers | length > 0)


- name: 'Checking cluster is dead'
  async_status: jid={{ item.ansible_job_id }}
  register: slv
  until: slv.finished
  retries: 240
  with_items: "{{ destruction_waitress.results }}"
  when: alive_servers is defined and (alive_servers | length > 0)

- name: destroy security group
  include: destroy_security_group.yml
