---

- name: initialize security group
  include: create_security_group.yml

- name: create master with ip pool
  os_server:
    state: present
    name: "{{ cluster_name }}-master"
    image: "{{ os_image }}"
    flavor: "{{ master_flavor }}"
    key_name: "{{ os_key_name }}"
    floating_ip_pools: "{{ floating_ip_pool }}"
    network: "{{ virtual_network }}"
    boot_from_volume: "{{ boot_from_volume }}"
    security_groups: "{{ cluster_name }}"
    meta: "hostname={{ cluster_name }}-master,group={{ cluster_name }}_master,owner={{ cluster_owner }}"
  retries: 3
  when:
    - floating_ip_pool != "None"
    - create_master_slave is defined and create_master_slave or create_master is defined and create_master


- name: create master without ip pool
  os_server:
    state: present
    name: "{{ cluster_name }}-master"
    image: "{{ os_image }}"
    flavor: "{{ master_flavor }}"
    key_name: "{{ os_key_name }}"
    auto_ip: no
#    floating_ip_pools: "{{ floating_ip_pool }}"
    network: "{{ virtual_network }}"
    boot_from_volume: "{{ boot_from_volume }}"
    security_groups: "{{ cluster_name }}"
    meta: "hostname={{ cluster_name }}-master,group={{ cluster_name }}_master,owner={{ cluster_owner }}"
  retries: 3
  when:
    - floating_ip_pool == "None"
    - create_master_slave is defined and create_master_slave or create_master is defined and create_master

- name: create slaves with ip pool
  os_server:
    state: present
    name: "{{ item }}"
    image: "{{ os_image }}"
    flavor: "{{ slaves_flavor }}"
    key_name: "{{ os_key_name }}"
    floating_ip_pools: "{{ floating_ip_pool }}"
    network: "{{ virtual_network }}"
    boot_from_volume: "{{ boot_from_volume }}"
    security_groups: "{{ cluster_name }}"
    meta: "hostname={{ item }},group={{ cluster_name }}_slaves,owner={{ cluster_owner }}"
  with_sequence: start=1 end={{ n_slaves if n_slaves > 0 else 1 }} format={{ cluster_name }}-slave-%d
  retries: 3
  when:
    - floating_ip_pool != "None"
    - create_master_slave is defined and create_master_slave or create_master is defined and create_master


- name: create slaves without ip pool
  os_server:
    state: present
    name: "{{ item }}"
    image: "{{ os_image }}"
    flavor: "{{ slaves_flavor }}"
    key_name: "{{ os_key_name }}"
    auto_ip: no
#    floating_ip_pools: "{{ floating_ip_pool }}"
    network: "{{ virtual_network }}"
    boot_from_volume: "{{ boot_from_volume }}"
    security_groups: "{{ cluster_name }}"
    meta: "hostname={{ item }},group={{ cluster_name }}_slaves,owner={{ cluster_owner }}"
  with_sequence: start=1 end={{ n_slaves if n_slaves > 0 else 1 }} format={{ cluster_name }}-slave-%d
  retries: 3
  when:
    - floating_ip_pool == "None"
    - create_master_slave is defined and create_master_slave or create_master is defined and create_master

- name: create storage with ip pool
  os_server:
    state: present
    name: "{{ cluster_name }}-storage"
    image: "{{ os_image }}"
    flavor: "{{ storage_flavor }}"
    key_name: "{{ os_key_name }}"
    floating_ip_pools: "{{ floating_ip_pool }}"
    network: "{{ virtual_network }}"
    boot_from_volume: "{{ boot_from_volume }}"
    security_groups: "{{ cluster_name }}"
    meta: "hostname={{ cluster_name }}-storage,group={{ cluster_name }}_storage,owner={{ cluster_owner }}"
  retries: 3
  when: floating_ip_pool != "None" and create_storage is defined and create_storage == true

- name: create storage without ip pool
  os_server:
    state: present
    name: "{{ cluster_name }}-storage"
    image: "{{ os_image }}"
    flavor: "{{ storage_flavor }}"
    key_name: "{{ os_key_name }}"
    auto_ip: no
    #    floating_ip_pools: "{{ floating_ip_pool }}"
    network: "{{ virtual_network }}"
    boot_from_volume: "{{ boot_from_volume }}"
    security_groups: "{{ cluster_name }}"
    meta: "hostname={{ cluster_name }}-storage,group={{ cluster_name }}_storage,owner={{ cluster_owner }}"
  retries: 3
  when: floating_ip_pool == "None" and create_storage is defined and create_storage == true
