---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Register server facts
      os_server_info:
        filters:
          metadata:
            group: "{{ cluster_name }}_{{ extended_role }}"
      no_log: True
      register: ip
    - debug: msg="{{ ip.openstack_servers[0].interface_ip if ip.openstack_servers[0].interface_ip != '' else ip.openstack_servers[0].private_v4 }}"
