---

- name: add postgresql repo
  become: yes
  shell: "sudo dnf install -yq https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
  args:
    executable: /bin/sh

- name: disable built-in postgresql
  become: yes
  shell: "dnf -yq module disable postgresql"
  args:
    executable: /bin/sh

- name: install postgres
  become: yes
  dnf:
    name: "postgresql{{ postgresql_version | replace('.','') }}-server"

# TODO: replace 'ignore_errors' with correct check of repeated init
- name: init postgresql cluster
  become: yes
  shell: "/usr/pgsql-{{ postgresql_version | replace('.','') }}/bin/postgresql-{{ postgresql_version | replace('.','') }}-setup initdb"
  args:
    executable: /bin/sh
  ignore_errors: yes

- name: enable and start postgresql server
  service:
    name: postgresql-{{ postgresql_version }}
    state: restarted
    enabled: yes

- name: install psycopg2
  become: yes
  dnf:
    name: python3-psycopg2