---

- name: Ensure epel repo present
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present

- name: update cache
  yum:
    update_cache: yes
    
- name: Install pip
  yum:
    name: python2
    state: present
    
- name: install pip3
  yum:
    name: python3
    state: present   

- name: install "@Development tools"
  yum:
    name: "@Development tools"

- name: install python3-devel
  yum:
    name: python3-devel

- name: install postgresql-libs
  yum:
    name: postgresql-libs

- name: install postgresql-devel
  yum:
    name: postgresql-devel

- name: install python-psycopg2
  yum:
    name: python-psycopg2
    
- name: add postgresql repo
  shell: "sudo yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm"
  args:
    executable: /bin/bash

- name: yum-config-manager --disable postgresql
  shell: "sudo yum-config-manager --disable postgresql"
  args:
    executable: /bin/bash

- name: install postgres
  shell: "sudo yum install -y postgresql{{ postgresql_version | replace('.','') }}-server"
  args:
    executable: /bin/bash

- name: init database for 9.6
  command: /usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ postgresql_version | replace('.','') }}-setup initdb
  when: postgresql_version == "9.6"
  register: result
  failed_when:
    - result.rc != 0
    - '"is not empty" not in result.stdout'
  changed_when:
    - result.rc == 0

- name: init database for 10, 11 or 12
  command: /usr/pgsql-{{ postgresql_version }}/bin/postgresql-{{ postgresql_version }}-setup initdb
  when: postgresql_version | int >= 10
  register: result
  failed_when:
    - result.rc != 0
    - '"is not empty" not in result.stdout'
  changed_when:
    - result.rc == 0

- name: enable and start postgresql server
  service:
    name: postgresql-{{ postgresql_version }}
    state: restarted
    enabled: yes
